export const MOCK_ADS = [
  {
    id: 1,
    name: "Valentina",
    age: 22,
    rating: 5,
    location: "Bogotá, Chapinero Alto",
    price: "$250.000 / hr",
    image: "../../public/15.jpg",
    description: "Servicio premium enfocado en la relajación absoluta. Compañía exclusiva en un ambiente diseñado para el confort y la discreción total.",
  },
  {
    id: 2,
    name: "Isabella",
    age: 24,
    rating: 5,
    location: "Medellín, El Poblado",
    price: "$350.000 / hr",
    image: "../../public/16.jpg",
    description: "Elegancia y distinción en cada encuentro. Experiencia de alto nivel para caballeros que buscan una compañía inteligente y sofisticada.",
  },
  {
    id: 3,
    name: "Camila",
    age: 21,
    rating: 4,
    location: "Cali, Ciudad Jardín",
    price: "$200.000 / hr",
    image: "../../public/17.jpg",
    description: "Carisma y dulzura. Me especializo en masajes tántricos y momentos de desconexión total. Disponible para encuentros exclusivos.",
  },
  {
    id: 4,
    name: "Sofia",
    age: 26,
    rating: 5,
    location: "Bogotá, Chicó Norte",
    price: "$450.000 / hr",
    image: "../../public/18.jpg",
    description: "Compañía de élite para eventos, cenas o encuentros privados. Una mujer políglota que entiende el valor de la exclusividad.",
  },
  {
    id: 5,
    name: "Elena",
    age: 23,
    rating: 5,
    location: "Medellín, Laureles",
    price: "$300.000 / hr",
    image: "../../public/19.jpg",
    description: "Amante de la buena conversación. Ofrezco un espacio seguro y lujoso donde el tiempo se detiene. Solo previa cita.",
  },
  {
    id: 6,
    name: "Martina",
    age: 25,
    rating: 4,
    location: "Barranquilla, Alto Prado",
    price: "$280.000 / hr",
    image: "../../public/21.jpg",
    description: "Belleza caribeña con un toque de clase europea. Disfruta de una velada inolvidable con la mejor atención de la ciudad.",
  },
  {
    id: 7,
    name: "Gabriela",
    age: 22,
    rating: 5,
    location: "Bogotá, Santa Ana",
    price: "$400.000 / hr",
    image: "../../public/22.jpg",
    description: "Estudiante de artes con un lado audaz. Me encanta explorar nuevas sensaciones en ambientes de total lujo y respeto.",
  },
  {
    id: 8,
    name: "Victoria",
    age: 28,
    rating: 5,
    location: "Medellín, Envigado",
    price: "$500.000 / hr",
    image: "../../public/images.jpg",
    description: "Experiencia GFE (Girlfriend Experience) de primer nivel. Sofisticación y madurez en cada detalle.",
  }
];
